### ISSUE TITLE
Issue: I'm not able to claim

### ISSUE THREAD

**Issue by BAPI-CH** [fetchai/deprecated-docs#1022]
As of today (2024-11-08), I can't claim my rewards from the Wallet (google extension). The button "Claim" doesn't appear
<img width="258" alt="image" src="https://github.com/user-attachments/assets/6578b45e-ebb1-42f0-a347-ef3aa99eccbc">

**Comment by Sophiestanworth** [comment]
> As of today (2024-11-08), I can't claim my rewards from the Wallet (google extension). The button "Claim" doesn't appear <img alt="image" width="258" src="https://private-user-images.githubusercontent.com/64914875/383449293-6578b45e-ebb1-42f0-a347-ef3aa99eccbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTU4MDUsIm5iZiI6MTczMDg5NTUwNSwicGF0aCI6Ii82NDkxNDg3NS8zODM0NDkyOTMtNjU3OGI0NWUtZWJiMS00MmYwLWEzNDctZWYzYWE5OWVjY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEyMTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmZhZmQwMDAwNGQ1NWRiMGJmMGE1MDBlY2Y1NGJkZTg5MmE5ZGQ4Y2FhMTY0MDQxMWVjMWUyZmRiMGRhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXjNrFb6U9PVS8kL5zhu9TVzEItt8c97szrp2dK5C6M">



> As of today (2024-11-08), I can't claim my rewards from the Wallet (google extension). The button "Claim" doesn't appear


Hey there @BAPI-CH!

If the "Claim" button isn’t showing in your wallet extension, try refreshing or reloading the page. If the issue persists, reach out to Fetch's support team for further assistance. A support ticket (ID: FET7638) has been created for you. Visit [Fetch Protocol Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat at the bottom right to connect with an agent.

Thank you for your patience!

**Comment by BAPI-CH** [comment]
> Sometimes browser extensions can be a bit glitchy. Have you tried refreshing the page or restarting the browser? If that doesn’t work, you might want to check if there’s an update available for the extension. Also, double-check if your wallet is properly connected and synced. @BAPI-CH

I did ieverything, but nothing's working.

**Comment by Annawoody** [comment]
Since you’ve done everything and it not working out guess you will have reach out to the support team  support live chat with the ticket ID FET07638
Please see the link below to our dedicated support line:
[Fetch protocol Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@BAPI-CH

**Comment by NikoDMT** [comment]
Hey there. This is likely because you've staked all of your FET and haven't left any liquid FET in your wallet. If you're able to send yourself 1 liquid FET you'll be able to claim your existing rewards. For context, claiming rewards is itself a transaction on the chain which is why it also requires gas to process. Transaction costs on the Fetch.ai mainnet are very close to zero but aren't zero. 

P.S Please ignore all support tickets. We don't process help requests with support tickets. All support tickets are likely a scam. Be vigilant. 

Hopefully this helps.

**Comment by BAPI-CH** [comment]
> Hey there. This is likely because you've staked all of your FET and haven't left any liquid FET in your wallet. If you're able to send yourself 1 liquid FET you'll be able to claim your existing rewards. For context, claiming rewards is itself a transaction on the chain which is why it also requires gas to process. Transaction costs on the Fetch.ai mainnet are very close to zero but aren't zero.
> 
> P.S Please ignore all support tickets. We don't process help requests with support tickets. All support tickets are likely a scam. Be vigilant.
> 
> Hopefully this helps.

Thank you a lot! Indeed, I didn't notice I had no FET available in my wallet. As soon as I sent one, everything was back.
Warm wishes

**Comment by devjsc** [comment]
Closing as looks like all has been resolved
