### ISSUE TITLE
Incorrect Use of "Checkout" vs. "Check Out" in Documentation

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#841]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

We should use "check out" when referring to the verb (e.g., "Please check out this feature"). We should use "checkout" when referring to the noun (e.g., "Proceed to checkout").

### Observed Behavior / Content

Most instances in our documentation incorrectly use "checkout" instead of "check out" when referring to the verb.

**Comment by devjsc** [comment]
Checkout, while a noun of referring to git/code is acceptable even if used as a verb due to the reference to a known act. Checkout in a phrase like “checkout this really cool x” is a verb, and should be check out, however in relation to a git repository or code base, I think 'checkout' is the right use of the word.

This is kinda like the word "hoover", while a noun, it's also a verb depending on it's use. I could be wrong of course, but I need examples of where this is an issue in your eyes 👍
