### ISSUE TITLE
Issue: <Issue Related to /guides/fetch-network/how-to-stake>

### ISSUE THREAD

**Issue by CFroede** [fetchai/deprecated-docs#882]
Hi i tried to connect my metamask wallet to fetch ai so i can stake FET, it seemed that everything went fine but i dont see my tokens. I've tried to delete the wallet and add again and the same happen.

**Comment by bradstevens1** [comment]
Hello @CFroede 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by NikoDMT** [comment]
Hey there. Ever since April of 2021 Fetch.ai has had it's own native network. With that being said we're also interoperable with Ethereum. This interoperability is why you can store erc20 FET on your metamask and execute transactions on the Ethereum base layer. However staking can only be done with native FET through the Fetch.ai browser extension wallet. If you wish to stake you can head on over to our docs and learn all about it: https://fetch.ai/docs/guides/fetch-network/how-to-stake#staking 

If you're holding erc20 FET you will also need to bridge them to the native network. You can read all about it here: https://fetch.ai/docs/guides/fetch-network/how-to-convert-fet-to-and-from-erc20 

In general the process is quite simple. First you bridge and then you stake. If this is your first time doing this you can try both bridging and staking with a small test amount first. Then proceed with the rest. Bridging usually takes a while (between 30 minutes to 4 hours (depending on ethereum network congestion and the amount of people looking to bridge)

**Comment by CFroede** [comment]
I've tried to bridge but it seems i dont have the options shwon on the documentation, what am I doing wrong? 
![bridge](https://github.com/user-attachments/assets/0953fa62-7e01-4ffe-ab1b-c381a02284e1)

**Comment by NikoDMT** [comment]
You can directly bridge from erc20 to native FET by using the bridge https://token-bridge.fetch.ai/ 

Ensure you've set up the Fetch.ai browser extension wallet and have a public address starting with fetch1... 

Here's a short step plan for erc20 to native FET 

1. Ensure you have the Metamask wallet ↗️ installed and that the ERC-20 FETs you want to convert are in this wallet.
2. Ensure you have the Fetch wallet installed: https://fetch.ai/docs/guides/fetch-network/fetch-wallet/web-wallet/get-started and that your Fetch.ai account is set up on it. This is where the native FETs will go to.
3.Go to the Token Bridge: https://token-bridge.fetch.ai/ 
4. Unlock the Metamask wallet if instructed to do so.
**5. Ensure the ERC-20 to Native tab is selected.**
6.The Ethereum address should be automatically filled in with the address of the active account on your Metamask wallet. Ensure that it is correct.
7.Insert your Fetch wallet address in the Native Address section.
8.Under Amount, enter the amount of tokens you wish to convert.
9Hit Transfer and allow the Token Bridge to connect with your wallet.

**Comment by CFroede** [comment]
How long does it take to show in my fetch wallet? I did it 10 min ago and still dont see anything

**Comment by NikoDMT** [comment]
It can take anywhere between half an hour to 4+ hours. There have also been instances of 24h+ waiting times but these are rare and we can fix them when they arise.

**Comment by abhifetch** [comment]
Hi @CFroede,

could you please confirm if it reflects in your wallet?

**Comment by CFroede** [comment]
Hi yes thnak you!!

**Comment by devjsc** [comment]
Closing issue as this looks to be resolved. Feel free to open again if you need any further help.
